name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: write-all

jobs:
  mikbot:
    uses: mikbot/mikbot-workflow/.github/workflows/mikbot-workflow.yml@v1.2.1
    secrets:
      GCP_ACCOUNT_KEY: ${{ secrets.GCP_ACCOUNT_KEY }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
